idle_bg = "#6871ff"
idle_fg = "#1e1d40"
info_bg = "#00c5c7"
info_fg = "#2e3440"
good_bg = "#43d426"
good_fg = "#2e3440"
warning_bg = "#fad000"
warning_fg = "#1e1d40"
critical_bg = "#f92a1c"
critical_fg = "#1e1d40"
separator = " "
alternating_tint_bg = "#44444400"
alternating_tint_fg = "#11111100"
