- name: Setup environment
  hosts: local

  tasks:
    - name: Set ParallelDownloads in pacman config
      become: true
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: '^#ParallelDownloads = \d+'
        replace: 'ParallelDownloads = 10'
        mode: 0644
      when: ansible_facts['distribution'] == 'Archlinux'

    - name: Register has_paru
      ansible.builtin.command: pacman -Q paru
      register: has_paru
      ignore_errors: true
      changed_when: has_paru.rc != 0
      when: ansible_facts['distribution'] == 'Archlinux'

    - name: Create the `aur_builder` user
      become: true
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel
      when: ansible_facts['distribution'] == 'Archlinux'

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: true
        validate: "visudo -cf %s"
        mode: 0440
      when: ansible_facts['distribution'] == 'Archlinux' and has_paru is failed

    - name: Install paru using makepkg if it isn't installed already
      kewlfft.aur.aur:
        name: paru
        use: makepkg
        state: present
      become: true
      become_user: aur_builder
      when: ansible_facts['distribution'] == 'Archlinux' and has_paru is failed

    - name: Install packages
      become: yes
      become_user: aur_builder
      kewlfft.aur.aur:
        use: paru
        state: present
        name:
          - ark
          - bat
          - curl
          - deluge-gtk
          - direnv
          - docker
          - docker-buildx
          - docker-compose
          - dolphin
          - dolphin-plugins
          - dunst
          - eza
          - ffmpegthumbs
          - firefox
          - fish
          - fisher
          - fnm-bin
          - gwenview
          - hyprland
          - hyprpaper
          - less
          - man
          - neovim
          - nfs-utils
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-cjk
          - noto-fonts-extra
          - openssh
          - pavucontrol
          - pipewire
          - polkit-kde-agent
          - pyenv
          - ripgrep
          - rofi
          - rust-analyzer
          - starship
          - stow
          - tree-sitter-cli
          - ttf-iosevkaterm-nerd
          - uwsm
          - vlc
          - waybar
          - wezterm
          - wl-clipboard
          - wireplumber
          - xdg-desktop-portal-hyprland

    - name: Remove the `aur_builder` user
      become: true
      ansible.builtin.user:
        name: aur_builder
        remove: true
        state: absent

    - name: Create directories
      ansible.builtin.command: mkdir -p $HOME/.ssh $HOME/config
      register: output
      changed_when: output.rc != 0

    - name: Install npm
      ansible.builtin.command: fnm install --lts
      register: output
      changed_when: output.rc != 0

    - name: Stow
      ansible.builtin.command: stow --verbose --restow --target=$HOME/.config --dir=../ config
      register: output
      changed_when: output.rc != 0

    - name: Install fish-ssh-agent
      ansible.builtin.command: fish -c "fisher install danhper/fish-ssh-agent"
      register: fish_ssh_agent
      changed_when: fish_ssh_agent.rc != 0

    - name: Enable sddm service
      become: true
      ansible.builtin.systemd:
        name: sddm.service
        enabled: true

    - name: Enable hyprpaper service
      ansible.builtin.systemd:
        name: hyprpaper.service
        scope: user
        enabled: true

    - name: Enable waybar service
      ansible.builtin.systemd:
        name: waybar.service
        scope: user
        enabled: true

    - name: Register user_shell
      ansible.builtin.shell: grep $USER /etc/passwd
      register: user_shell
      changed_when: user_shell.rc != 0

    - name: Change shell
      ansible.builtin.shell:
        cmd: chsh --shell $(command -v fish)
        stdin: "{{ ansible_become_password }}"
      when: user_shell.stdout is not regex("fish$")
